version: '3.8'

services:
  # Proxy inverso Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - contacts-network

  # Frontend React
  frontend:
    image: agusklos/frontend-contacts:latest
    environment:
      - VITE_REACT_APP_API_URL=/api
      - VITE_REACT_APP_API_BASE_URL=/api
    restart: unless-stopped
    networks:
      - contacts-network

  # Backend API
  backend:
    image: agusklos/backend-contacts:latest
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=contacts_db
      - NODE_ENV=production
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - contacts-network

  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=contacts_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - contacts-network

volumes:
  mysql_data:

networks:
  contacts-network:
    driver: bridge