version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3002:3001"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=contacts_db
      - NODE_ENV=production
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - contacts-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=contacts_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - contacts-network

volumes:
  mysql_data:

networks:
  contacts-network:
    driver: bridge
